POST http://localhost:5000/books
Content-Type: application/json;charset=utf-8

{
    "author": "retdsf",
    "book_name": "sdf",
    "book_number": "003",
    "book_prize": 39.9,
    "book_publisher": "dfs",
    "book_type": "sdf"
}

###

GET http://localhost:5000/books
Accept: application/json;charset=utf-8

###

PUT http://localhost:5000/books/3
Content-Type: application/json;charset=utf-8

{
    "author": "ttt",
    "book_name": "sdf",
    "book_number": "003",
    "book_prize": 72.3,
    "book_publisher": "dfes111",
    "book_type": "swedf"
}

###

DELETE http://localhost:5000/books/3
Accept: application/json
